layout: stacked
style: dark

plugins:
    - jekyll-octicons
    - jekyll-github-metadata
    - jemoji

permalink: /:year/:month/:day/:title/

defaults:
    - scope:
          path: '' # an empty string here means all files in the project
          type: 'posts'
      values:
          layout: 'post'

projects:
    sort_by: pushed
    # sort_by options:
    #   - pushed
    #   - stars
    limit: 12
    exclude:
        archived: false
        forks: true
        projects:
        # - repo-name

social_media:
    # behance: your_username
    # dribbble: your_username
    # facebook: your_username
    # hackerrank: your_username
    # instagram: your_username
    # keybase: your_username
    linkedin: jose-gracia
    # mastodon: your_username
    # medium: your_username
    stackoverflow: 9630043
    # telegram: your_username
    # twitter: your_username
    # unsplash: your_username
    # vk: your_username
    website: https://jgracia.es/
    # youtube: your_username

topics:
    - name: Symfony
      web_url: https://github.com/topics/symfony
      image_url: https://raw.githubusercontent.com/github/explore/d0c5a5e31e1776ad62379ef5f6b703bcf107d3a3/topics/symfony/symfony.png

    - name: Angular
      web_url: https://github.com/topics/angular
      image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/angular/angular.png

    - name: Linux
      web_url: https://github.com/topics/linux
      image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/linux/linux.png

    - name: TypeScript
      web_url: https://github.com/topics/typescript
      image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/typescript/typescript.png

    - name: Vue.js
      web_url: https://github.com/topics/vue
      image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/vue/vue.png

    - name: Node.js
      web_url: https://github.com/topics/nodejs
      image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/nodejs/nodejs.png

    - name: PHP
      web_url: https://github.com/topics/php
      image_url: https://raw.githubusercontent.com/github/explore/ccc16358ac4530c6a69b1b80c7223cd2744dea83/topics/php/php.png

    - name: MySQL
      web_url: https://github.com/topics/mysql
      image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/mysql/mysql.png

    - name: Docker
      web_url: https://github.com/topics/docker
      image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/docker/docker.png
